stages:
  - build
  - publish

build:iso:
  image: ulm0/linuxkit:v0.8
  services:
    - docker:stable-dind
  stage: build
  before_script:
    - apk add --no-cache make
  script:
    - make
  artifacts:
    paths:
      - k3s-*
  only:
    - master
    - tags
    - external_pull_requests

github:release:
  image: ulm0/deliver:v1.1.0
  stage: publish
  variables:
    OVERRIDE_RELEASE: "true"
    RELEASE_CHECKSUM: sha512
    RELEASE_DESCRIPTION: "k3s on linuxkit"
    RELEASE_FILES: $CI_PROJECT_DIR/k3s-*
    RELEASE_NAME: $CI_COMMIT_TAG
  script:
    - deliver
  only:
    - tags
  dependencies:
    - build:iso
