kernel:
  image: linuxkit/kernel:5.4.39
  cmdline: "console=ttyS0 page_poison=1"
init:
  # - linuxkit/vpnkit-expose-port:v0.8
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
  - linuxkit/ca-certificates:v0.8
onboot:
  # support metadata for optional config in /run/config
  - name: metadata
    image: linuxkit/metadata:v0.8
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: sysfs
    image: linuxkit/sysfs:v0.8
  - name: binfmt
    image: linuxkit/binfmt:v0.8
  - name: format
    image: linuxkit/format:v0.8
  - name: mount_var_lib
    image: linuxkit/mount:v0.8
    command: ["/usr/bin/mountie", "/var/lib/"]
  - name: mount_etc
    image: linuxkit/mount:v0.8
    command: ["/usr/bin/mountie", "/etc/rancher/"]
  # - name: mount-vpnkit
  #   image: alpine:3.11
  #   binds:
  #       - /var/:/host_var:rbind,rshared
services:
  - name: acpid
    image: linuxkit/acpid:v0.8
  - name: ntpd
    image: linuxkit/openntpd:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: host-timesync-daemon
    image: linuxkit/host-timesync-daemon:v0.8
  - name: k3s
    image: rancher/k3s:v1.18.4-k3s1
    capabilities:
      - all
    net: host
    command: 
      - /bin/k3s
      - server
      - --kubelet-arg=cgroup-root=kubepods
      - --kubelet-arg=kube-reserved-cgroup=podruntime
      - --kubelet-arg=system-reserved-cgroup=systemreserved
    mounts:
      - type: bind
        source: /sys/fs/cgroup
        destination: /sys/fs/cgroup
        options: ["rw","rbind","rshared","nosuid","noexec","nodev","relatime"]
    runtime:
      cgroups:
        - kubepods
        - podruntime
        - systemreserved
    #   mkdir:
    #     - /etc/rancher
    #     - /var/lib/rancher
    binds:
      # - /etc/rancher:/etc/rancher
      - /etc/resolv.conf:/etc/resolv.conf
      - /lib/modules:/lib/modules
      - /dev/kmsg:/dev/kmsg
      # - /var/lib/rancher:/var/lib/rancher
    rootfsPropagation: shared
  - name: getty
    image: linuxkit/getty:v0.8
    env:
      - INSECURE=true

trust:
  org:
    - linuxkit
    - library
