name: Build ISO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:19.03.12
    services:
      dind:
        image: docker:19.03.12-dind
    steps:
      - name: build
        run: |
          apk add --no-cache make
          ls
          make
      - name: build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: k3s
          path: "k3s-*"
